seed: 42
do_train: True
do_predict: False

# file path #
output_dir: output/tendency
train_file: ../data/original/train.json
validation_file: ../data/original/test.json

# model config #
model_name_or_path: /data3/MODELS/ms-marco-electra-base
hidden_size: 768

# training config #
num_train_epochs: 1
max_seq_length: 160
dataloader_num_workers: 2

per_device_train_batch_size: 32
per_device_eval_batch_size: 32
gradient_accumulation_steps: 1
learning_rate: 3.0e-5
weight_decay: 1.0e-5
warmup_ratio: 0.1
max_grad_norm: 1
optim: adamw_torch

logging_strategy: steps
logging_steps: 100
evaluation_strategy: steps
evaluation_steps: 200
save_strategy: "epoch"
save_total_limit: 1